### ISSUE TITLE
Support for refunds

### ISSUE THREAD

**Issue by gadelkareem** [thephpleague/omnipay-mollie#25]
Is there a plan to add support for refunds API?

**Comment by kayladnls** [comment]
Not currently but I'd be happy to put the feature request on the V3 roadmap.

**Comment by lukeholder** [comment]
@kayladnls Are you saying refunds would not be possible without v3? Anything technically stopping us from adding refund support before then?

**Comment by delatbabel** [comment]
Nothing would stop you adding it if you wanted to send in a PR.

**Comment by lukeholder** [comment]
thanks @delatbabel will do

**Comment by Archanium** [comment]
#26 solves this. :)

**Comment by lukeholder** [comment]
thanks @Archanium !
