### ISSUE TITLE
Update omnipay/common version to use this repo with symfony 3.0

### ISSUE THREAD

**Issue by bijsterdee** [thephpleague/omnipay-mollie#32]
When using symfony ~3.0, composer install fails because it requires omnipay/common version ~2.2.
omnipay/common version 2.2 requires  "symfony/http-foundation": "~2.1".

Can you update composer.json to use a newer version of omnipay/common?

**Comment by barryvdh** [comment]
Nope, but will be done in v3

**Comment by bijsterdee** [comment]
@barryvdh Can you please explain in more detail why not and what v3 is? 
Current release is v3.1, do you mean v3.3?
And do you have a timeframe, when this version will be released?

**Comment by barryvdh** [comment]
No timeframe. I mean for omnipay-common: https://github.com/thephpleague/omnipay-common/issues/128
