### ISSUE TITLE
We (Mollie) would like to get involved

### ISSUE THREAD

**Issue by willemstuursma** [thephpleague/omnipay-mollie#45]
Hi 👋!

This is Willem from Mollie.

We've been watching this package for a while now at Mollie and we'd like to get involved to bring the highest quality possible driver for Mollie merchants to Omnipay.

To whom can I reach out to discuss this? You can reach me at willem@mollie.com.

**Comment by barryvdh** [comment]
Awesome :)
I'll email you.
