### ISSUE TITLE
Tag 4.0.1 as "latest" in Github

### ISSUE THREAD

**Issue by ruudk** [thephpleague/omnipay-mollie#46]
This looks weird:
<img width="819" alt="screen shot 2018-05-25 at 11 19 27" src="https://user-images.githubusercontent.com/104180/40536785-8627cf44-600d-11e8-9f31-d84fef1c6b6f.png">

**Comment by barryvdh** [comment]
Done.

**Comment by ruudk** [comment]
I see this for a lot of packages btw, stripe, paypal, etc.
