### ISSUE TITLE
Transaction failed all the time after new update

### ISSUE THREAD

**Issue by akki44** [thephpleague/omnipay-mollie#51]
Hello, after new update I am getting 404 bad request all the time. What is the exact issue?

**Comment by Smitsel** [comment]
Hi @akki44, do you have some more details?
What is inside the ``$response->getMessage()``?

**Comment by akki44** [comment]
The JSON request do not represent an object.

**Comment by Smitsel** [comment]
Can you place the code you are using? Then i can probably help u.
Make sure you remove your API key though.

**Comment by nickurt** [comment]
Hi @Smitsel,

While I was working on my fork (for support Mollie Connect) I hitted this problem aswell [for all GET requests], the problem is in the sendRequest [AbstractMollieRequest] method

```php
protected function sendRequest($method, $endpoint, array $data = null)
{
	$response = $this->httpClient->request(
            $method,
            $this->baseUrl . $this->apiVersion . $endpoint,
            [
                'Authorization' => 'Bearer ' . $this->getApiKey()
            ],
            json_encode($data)
        );

	// fixed it with version below ...

	$response = $this->httpClient->request(
            $method,
            $this->baseUrl . $this->apiVersion . $endpoint,
            [
                'Authorization' => 'Bearer ' . $this->getApiKey()
            ],
            ($method == 'GET') ? null : json_encode($data)
    );
}
```

PHP7.2.8
GuzzleDriver

**Comment by Smitsel** [comment]
Thanks guys, i've created a PR for this.
