### ISSUE TITLE
Research: integrate the Orders API to support Klarna

### ISSUE THREAD

**Issue by Smitsel** [thephpleague/omnipay-mollie#54]
We are currently in the process of creating a brand new API to support payment methods which use an authorise and capture flow. You can read more about that here: https://docs.mollie.com/orders/overview

Now im researching if we could add this to the omnipay mollie gateway and i'm running into some difficulties. There is some support for authorising and capturing documented here:
https://omnipay.thephpleague.com/api/authorizing/

The first problem is sending the shopping cart to the mollie API. Which is solvable by adding certain fields and requirements to the `purchase(array $options)` call on the gateway:
- `lines`
- `shippingAddress` / `billingAddress`
When these are being sent we can just do the create order call on the Mollie API and send the customer to the offsite payment gateway.

From here the customer could select Klarna as a payment option, which will authorise the order and send the customer to their hosted payment page. That results in the order being authorised. Which from a shoppers perspective means the order is placed but for the merchant it means they should still capture.

This is the part i'm having trouble with to figure out how to implement it. 
I think we should document well that when a purchase comes back with authorised state the integrators of this package should do a capture call with the required parameters as described in our shipment Api.

Do you have any thoughts about this @barryvdh?
Or do you see any problems when implementing it as described above?

**Comment by roelvanduijnhoven** [comment]
@willemstuursma Are there plans from Mollie to integrate Klarna into this repo? Would really help us!

And thanks again for the previous work on adding multicurrency support to this library :clap:

**Comment by willemstuursma** [comment]
We're not really sure how to add it to this library, hence this issue.

@roelvanduijnhoven To be frank, I think you would be better off implementing orders through our own library directly.

**Comment by roelvanduijnhoven** [comment]
Excuse me @willemstuursma; was not aware that @Smitsel was part of your team :).

> To be frank, I think you would be better off implementing orders through our own library directly.

Do you say that that because you think it will take some time before this change will land in this repo? Or because it is incompatible; and (looks like it) can't be integrated?

**Comment by Smitsel** [comment]
For Klarna to be available through this library we need to use our new Mollie Orders API.
Unfortunately the abstraction that Omnipay offers does not have extensive support for submitting orders and lines through the gateway.

So it is incompatible, unfortunately. And if we would, it would require a lot of customisation. 

Therefor the best advise is to indeed implement the Mollie PHP SDK because it will probably be the same amount of work as implementing this library with orders.

Please have a look at: https://github.com/mollie/mollie-api-php

**Comment by barryvdh** [comment]
Yeah there is an `ItemBag` with `Items` which should represent a cart / order lines, but it's not really implemented the same in all gateways (or documented at all).  There is an old discussion here: https://github.com/thephpleague/omnipay/issues/323
Perhaps it could be a good starting point for a new minor release, what do you think @judgej ?

**Comment by barryvdh** [comment]
I'm gonna look into this and try to integrate it!

**Comment by barryvdh** [comment]
Initial implementatie here: https://github.com/thephpleague/omnipay-mollie/pull/58
Let's continue the discussion there.
