### ISSUE TITLE
maximumAmount in getPaymentMethods

### ISSUE THREAD

**Issue by lenvanessen** [thephpleague/omnipay-mollie#79]
Hi There,

According to Mollie, they send the `maximumAmount` as part of the response of their `v2/methods` endpoint.
Anyway we can get this into the `Omnipay\Mollie\Message\Response\PaymentMethod`?

We need it to check if a payment method is usable for a specific order, depending on the height of the order. For instance, creditcard is capped at 1000 euros.

**Comment by willemstuursma** [comment]
You can also send the order amount to Mollie and they will filter the methods for you. This way, you don't have to keep your application in sync.

**Comment by lenvanessen** [comment]
Awesome, I rest my case
